### ISSUE TITLE
Interledger setup

### ISSUE THREAD

**Issue by kopnin** [interledger/five-bells-ledger#260]
Hi,

I would like to try Interledger with my custom ledgers. Could you, please, clarify how to start? 
I wanna run something like red.ilpdemo.org + wallet in private net. 

In my opinion, I should use ilp-client to make a payments (and receive payments) from client side. Also, I need a private Interleger with five-bells-connector and five-bells-ledger to authorize clients and transfer assets. But what is ilp-core, ilp-plugin-bells, five-bells-sender and other. I little bit confused how to use it all together, and what code I need to implement to work with Interledger.

Thanks advance.

**Comment by emschwartz** [comment]
Hi @kopnin,

Do you want to use Interledger with an existing ledger you have or do you want to run the full "five-bells" reference implementation stack? To see most of the reference components working together I'd recommend checking out the [`five-bells-demo`](https://github.com/interledger/five-bells-demo).

Here's a brief rundown of the full stack:

* [`five-bells-wallet-client`](https://github.com/interledger/five-bells-wallet-client) is a high level client for sending payments via the wallet
* [`five-bells-wallet`](https://github.com/interledger/five-bells-wallet) is what you see at red.ilpdemo.org and blue.ilpdemo.org. It's a layer on top of the ledger and the core Interledger Protocol that adds UI and a number of additional features deliberately left out of core ILP.
* [`js-ilp`](https://github.com/interledger/js-ilp) is a low-level client for interacting directly with ILP.
* [`js-ilp-core`](https://github.com/interledger/js-ilp-core) is used by `js-ilp` and will be used by the connector. It includes key ILP functionality, like interfacing with the [ledger plugins](https://github.com/interledger/rfcs/blob/master/0004-ledger-plugin-interface/0004-ledger-plugin-interface.md) (e.g. [`ilp-plugin-bells`](https://github.com/interledger/js-ilp-plugin-bells)) but you probably won't need to use it directly.
* [`five-bells-connector`](https://github.com/interledger/five-bells-connector) is an implementation of a connector one could run to enable interledger payments across two ledgers
* [`five-bells-ledger`](https://github.com/interledger/five-bells-ledger) is a reference implementation of a basic ledger that supports all of the Interledger transport protocols. If you want to get Interledger set up on your own you could either run this ledger (and the client and sender would use the [`ilp-plugin-bells`](https://github.com/interledger/js-ilp-plugin-bells) to connect to it) or you could run your own type of ledger and write a new [ledger plugin](https://github.com/interledger/rfcs/blob/master/0004-ledger-plugin-interface/0004-ledger-plugin-interface.md) (e.g. [`ilp-plugin-bells`](https://github.com/interledger/js-ilp-plugin-bells)) for it.
* [`five-bells-demo`](https://github.com/interledger/five-bells-demo) spins up a network of ledgers and connectors on your machine and has a visualization running on top of them to illustrate the flow of ILP payments.

**Comment by kopnin** [comment]
Thanks!

Yes, I want to run the full "five-bells" reference implementation stack. And I would like to connect to my Blockchain. 

You mentioned about possibility to use the Blockchain protocols [](https://interledger.org/rfcs/0001-interledger-architecture/#example-protocols). In this case I don't need to use _five-bells-ledger_, isn't it? In this case, is Blockchain used as a _Ledger Layer_? 
Also, you wrote that connectors work with Ledger protocol via js-ilp-core. It mean that I need to implement ledger plugin for my Blockchain and configure _five-bells-connector_ to work over my plugin?

**Comment by emschwartz** [comment]
Correct, you don't need the `five-bells-ledger`. To support your blockchain you'll need to implement a [ledger plugin](https://github.com/interledger/rfcs/blob/master/0004-ledger-plugin-interface/0004-ledger-plugin-interface.md) for it. We're in the process of refactoring the connector and sending/receiving client to work out of the box with new ledger plugins.

The `five-bells-sender` is the sending client we've been using to initiate payments. It still assumes it's talking to a `five-bells-ledger`. We're working on the `js-ilp` client, which uses the `js-ilp-core`, which will be able to use any ledger plugin that exposes that interface. This isn't quite done but it'll be done within the next couple of weeks.

Note that the wallet assumes it's talking to a `five-bells-ledger` and I'm not sure if we're going to adapt that to different kinds of ledgers, since it's primarily meant for demos.

**Comment by justmoon** [comment]
> I'm not sure if we're going to adapt that to different kinds of ledgers

Probably not. A wallet is very tightly integrated with its underlying ledger and uses many more features than ledger plugins provide (create account, view history, etc.), so if we made a wallet for another ledger we'd likely fork five-bells-wallet rather than try to keep support for multiple ledgers in one codebase.

The easiest way to get an interledger enabled wallet for another ledger would be to add support into an existing wallet app. So for Bitcoin it could be added to Webcoin for instance.

**Comment by kopnin** [comment]
Thanks, Evan and Stefan! Cool answers!

Wallet it's just a high level application. Sample wallet is good for demonstration reason. Normally, we have to design a new application (or integrate to existing app as said Stefan). 

Regarding to five-bells-sender - do you recommend to use this abstraction layer to submit payments, or I should work directly with my ledger? Do you have plans to do sender as universal payment framework (to work via any ledger plagin)?

Let me summarize, please: 
In my case I need
1. Implement ledger plagin
2. In nearest future, connectors will work with any ledger plagin implementation. But at this moment I can not to connect it to my own ledger plagin. (Looks like a blocker)
3. Implement high level application to operate with payments (similar with five-bells-wallet)
4. Adopt five-bells-sender to my ledger to submit payments. 
5. Receive payments via ledger plugin

**Comment by emschwartz** [comment]
We're working on an ILP client that will use the same ledger plugin framework as the connector, which you would use to send and receive payments. You're right that the client and connectors working with different ledger plugin is a blocker -- this is the top of our priority list right now. In any case, it may be worth starting on the ledger plugin because the client and connector should be ready to use it within a week or two.

**Comment by kopnin** [comment]
Cool! Thanks for answers. 

Looking forward for any updates.
