### ISSUE TITLE
Connectors and transaction states

### ISSUE THREAD

**Issue by kopnin** [interledger/five-bells-ledger#266]
Hello,

I read more detailed information about connectors and I have couple of questions. 

1) Who are manage connectors? 
I mean, is it predefined connectors by Interledger administrator? Or every clients who are implemented Ledger plugin could be a connector? Who is determine relationships between connectors?

2) How other connectors will know about me? 
E.g someone provided me Interledger network and I would like to use it to receive the assets. I have to have an account. Where is my account stored? Does any connectors have my account details?

3) Cryptography escrow. 
Is it means that every transaction are stored on each connectors's ledger? What information are stored into the connector's ledger? Could I use the connector or Interledger to get transfer status if my client was stopped unexpectedly?

Thanks advance

**Comment by emschwartz** [comment]
Interledger is purely a protocol so there's no Interledger administrator. Theoretically, anyone could serve as a connector. In practice I would expect most of the larger ones to be run by businesses that specialize in currency trading. All it takes on the technical side is to run an instance of the connector code and hold accounts at 2+ ledgers.

The relationship between connectors is an interesting question. At first we were thinking that connectors would discover one another automatically. This presents a number of challenges though, because connectors will be judged on their reliability as well as the reliability of all of the next hops they select. It seems like any algorithm for determining the reliability of connectors would be gamed. For the moment we're thinking that connectors would manually "peer" with one another.

Connectors will use your ILP address to find you. Your account is stored on whatever ledger you choose to use. [This doc](https://github.com/interledger/rfcs/blob/master/0003-interledger-protocol/0003-interledger-protocol.md) needs to be updated with the very latest thinking but the basic idea is as follows. If you have an account on a small and not very well known ledger, you would provide your address in terms of a more well known one. So you might be `ilp:bitcoin/coinbase/other-ledger/9823000293000` (where the last one is your actual account. If I'm trying to pay you, the connectors near me won't necessarily know `coinbase` or the `other-ledger` but they would know how to get to `bitcoin` and from there a connector would know how to get to `coinbase` and then `other-ledger` and then to your account. 

Every local transfer that goes through a particular ledger will be stored on that ledger and use that ledger's cryptographic hold functionality to secure the larger payment it's a part of. As far as the protocol is concerned, the connector only needs to know that it received money (or a held transfer) from someone, and it needs to know the general direction it is going in to be able to forward it to the next connector on the next ledger. [This](https://github.com/interledger/rfcs/blob/master/0004-ledger-plugin-interface/0004-ledger-plugin-interface.md#replytotransfer) isn't fully fleshed out but we're expecting that errors would be reported back along the chain of connectors so you hear about failures.

**Comment by kopnin** [comment]
Regarding ilp address: every ledger has at _least_ one connector, in every ledgers we can create additional connectors, isn't it? 

When I connect a new ledger, I should 
- setup connector, 
- explicit assign **ilp address**  to it (ilp:my_ledger\ )
- and connect directly with other ones. 

When message will come to _ilp:my_ledger_ - connector will processed transfer and communicate with ledger via js_ilpcore.

Is it correct?

**Comment by emschwartz** [comment]
Right now most ledgers have 0 connectors :) -- but we're hoping that changes soon. Technically all you need to create a connector is an account on a couple of ledgers.

You're correct about the steps. If your ledger isn't well known you might want to give it an address that starts with another more well known ledger.

When someone sends a transfer to your connector, the notification will be handled by your ledger plugin, which is included in `js-ilp-core`, which is used by the connector.

**Comment by kopnin** [comment]
Cool! I believe the situation will change =)

Thanks for an excellent and fast answers!

**Comment by emschwartz** [comment]
They're good questions so I'm happy to help. What kind of ledger/blockchain are you interested in connecting?

**Comment by kopnin** [comment]
I just research the market and different existing ledgers. I would like to try Interledger with one of the most popular platform like Ethereum or Eris.

Evan, could I take your time a little more. I read about Notaries. In white paper you mentioned about consensus engine (PBFT/Tangaroa). Is it means that Notaries have a local storage to store some transaction information? Is it immutable? What storage do you use? 

And could you, please, slightly open the security part. How the Notaries validate the transactions? Do they get a public keys from participants? 

My apologies for a lot of questions.

**Comment by emschwartz** [comment]
Gotcha. We're going to be discussing cryptocurrency ledger plugins tomorrow morning on the [Interledger Community Group call ](https://lists.w3.org/Archives/Public/public-interledger/2016Jun/0011.html) in case you're interested.

Notaries actually don't need to validate transactions. Unlike validators in a blockchain, all they need to do is check whether a valid fulfillment for a specific condition was received before a certain timeout. Notaries do use a database to store the cases they are part of. The participants submit the "case" to the notary, which includes the condition that needs to be fulfilled, the expiry, and the people to notify about the outcome.

**Comment by kopnin** [comment]
Cool! Thanks for invitation, I will
